platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

#ignore all warnings from all pods
inhibit_all_warnings!

target 'WWDC' do
  pod 'Reveal-iOS-SDK', '~> 1.6.1', :configurations => ['Debug']     
end



